# Generated by Django 5.0.6 on 2024-07-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_Name', models.CharField(max_length=25)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=25)),
            ],
        ),
    ]
